version: '3.7'

services:
  app:
    container_name: app
    build: ./
    depends_on:
      - postgres
      - redis
      - nats
    command: "npm start"
    working_dir: /usr/src/vending_machine
    ports:
    - "7000:7000"
    environment: 
      port: 7000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_CONNECTION_URL: postgres://postgres:password@postgres:5432/vendingmachine
    networks: 
      - webnet
    volumes: 
      - ./:/usr/src/vending_machine
      - ./usr/src/vending_machine/node_modules
    links: 
      - redis
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: vendingmachine
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks: 
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks: 
      - webnet

  nats:
    image: nats-streaming:0.17.0
    ports:
        - "4222:4222"
        - "18222:8222"
    command:
        - "--cluster"
        - "nats://0.0.0.0:6222"
        - "--cluster_id"
        - nats-streaming
        - "--clustered"
        - "--cluster_bootstrap"
        - "--cluster_log_path"
        - /data/log
        - "--cluster_node_id"
        - nats-streaming-1
        - "--cluster_raft_logging"
        - "--debug"
        - "--dir"
        - /data/msg
        - "--http_port"
        - "8222"
        - "--port"
        - "4222"
        - "--store"
        - file
        - "--stan_debug"
        - "--hb_interval"
        - 2s
        - "--hb_fail_count"
        - "1"
        - "--hb_timeout"
        - 5s
    volumes:
        - "./nats-streaming-1:/data"
    networks:
        - main
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.255.0/24
      driver: default
  webnet:
    
volumes:
  pgdata:
