version: '3.7'

services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: vendingmachine
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  pgdata:
